### ISSUE TITLE
.gitmodules

### ISSUE THREAD

**Issue by olehsamoilenko** [omiroshn/FunctionalProgrammingFIT#1]
Hello
It's a good idea to get familiar with .gitmodules file
It gives an opportunity to avoid repo duplication
An example is [here](https://github.com/olehsamoilenko/fractol)
Have a good day and good luck!

**Comment by omiroshn** [comment]
@olehsamoilenko senk u wery mannch!!! ay appresiate ur help and su(ck)pport
в данном случае мне нужны были новые копии репозиториев
